import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding categories...");

  // Get all parents first
  const parentSlugs = [...new Set(categories.map(c => c.parent).filter((p): p is string => p !== null))];

  // Upsert parent categories
  for (const cat of categories.filter(c => !c.parent)) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });
  }

  // Get all parent IDs in one query
  const existingParents = await prisma.category.findMany({
    where: { slug: { in: [...parentSlugs] } },
    select: { slug: true, id: true },
  });
  const parentMap = Object.fromEntries(existingParents.map(p => [p.slug, p.id]));

  // Upsert children in batches of 50
  const children = categories.filter(c => c.parent);
  for (let i = 0; i < children.length; i += 50) {
    const batch = children.slice(i, i + 50);
    await Promise.all(
      batch.map(cat => {
        const parentId = parentMap[cat.parent!];
        if (!parentId) {
          console.warn(`Parent not found: ${cat.name} -> ${cat.parent}`);
          return;
        }
        return prisma.category.upsert({
          where: { slug: cat.slug },
          update: { name: cat.name, parentId },
          create: { name: cat.name, slug: cat.slug, parentId },
        });
      })
    );
    console.log(`  Batch ${i / 50 + 1}/${Math.ceil(children.length / 50)} done`);
  }

  console.log(`Done! ${categories.length} categories created.`);
}

// Copy the categories array from seed-categories.ts
const categories = [
  { id: 1, name: "Electronics", slug: "electronics", parent: null },
  { id: 2, name: "Smartphones", slug: "smartphones", parent: "electronics" },
  { id: 3, name: "Android Phones", slug: "android-phones", parent: "electronics" },
  { id: 4, name: "iPhones", slug: "iphones", parent: "electronics" },
  { id: 5, name: "Tablets", slug: "tablets", parent: "electronics" },
  { id: 6, name: "Laptops", slug: "laptops", parent: "electronics" },
  { id: 7, name: "Gaming Laptops", slug: "gaming-laptops", parent: "electronics" },
  { id: 8, name: "Desktop PCs", slug: "desktop-pcs", parent: "electronics" },
  { id: 9, name: "Monitors", slug: "monitors", parent: "electronics" },
  { id: 10, name: "Gaming Monitors", slug: "gaming-monitors", parent: "electronics" },
  { id: 11, name: "Cameras", slug: "cameras", parent: "electronics" },
  { id: 12, name: "DSLR Cameras", slug: "dslr-cameras", parent: "electronics" },
  { id: 13, name: "Action Cameras", slug: "action-cameras", parent: "electronics" },
  { id: 14, name: "Security Cameras", slug: "security-cameras", parent: "electronics" },
  { id: 15, name: "Smart Watches", slug: "smart-watches", parent: "electronics" },
  { id: 16, name: "Fitness Bands", slug: "fitness-bands", parent: "electronics" },
  { id: 17, name: "Headphones", slug: "headphones", parent: "electronics" },
  { id: 18, name: "Earbuds", slug: "earbuds", parent: "electronics" },
  { id: 19, name: "Speakers", slug: "speakers", parent: "electronics" },
  { id: 20, name: "Bluetooth Speakers", slug: "bluetooth-speakers", parent: "electronics" },
  { id: 21, name: "Gaming Consoles", slug: "gaming-consoles", parent: "electronics" },
  { id: 22, name: "PlayStation", slug: "playstation", parent: "electronics" },
  { id: 23, name: "Xbox", slug: "xbox", parent: "electronics" },
  { id: 24, name: "Nintendo", slug: "nintendo", parent: "electronics" },
  { id: 25, name: "Computer Accessories", slug: "computer-accessories", parent: "electronics" },
  { id: 26, name: "Mobile Accessories", slug: "mobile-accessories", parent: "electronics" },
  { id: 27, name: "Chargers", slug: "chargers", parent: "electronics" },
  { id: 28, name: "Power Banks", slug: "power-banks", parent: "electronics" },
  { id: 29, name: "Cables", slug: "cables", parent: "electronics" },
  { id: 30, name: "Routers", slug: "routers", parent: "electronics" },
  { id: 31, name: "Smart Home", slug: "smart-home", parent: "electronics" },
  { id: 32, name: "TVs", slug: "tvs", parent: "electronics" },
  { id: 33, name: "Projectors", slug: "projectors", parent: "electronics" },
  { id: 34, name: "Drones", slug: "drones", parent: "electronics" },
  { id: 35, name: "Printers", slug: "printers", parent: "electronics" },
  { id: 36, name: "VR Devices", slug: "vr-devices", parent: "electronics" },
  { id: 37, name: "Graphic Cards", slug: "graphic-cards", parent: "electronics" },
  { id: 38, name: "Processors", slug: "processors", parent: "electronics" },
  { id: 39, name: "Storage Devices", slug: "storage-devices", parent: "electronics" },
  { id: 40, name: "Motherboards", slug: "motherboards", parent: "electronics" },
  { id: 41, name: "Cooling Fans", slug: "cooling-fans", parent: "electronics" },
  { id: 42, name: "Networking Devices", slug: "networking-devices", parent: "electronics" },
  { id: 43, name: "Car Electronics", slug: "car-electronics", parent: "electronics" },
  { id: 44, name: "Audio Systems", slug: "audio-systems", parent: "electronics" },
  { id: 45, name: "Smart Devices", slug: "smart-devices", parent: "electronics" },
  { id: 46, name: "Clothing", slug: "clothing", parent: null },
  { id: 47, name: "Men's Fashion", slug: "mens-fashion", parent: "clothing" },
  { id: 48, name: "T-Shirts", slug: "t-shirts", parent: "clothing" },
  { id: 49, name: "Shirts", slug: "shirts", parent: "clothing" },
  { id: 50, name: "Pants", slug: "pants", parent: "clothing" },
  { id: 51, name: "Jeans", slug: "jeans", parent: "clothing" },
  { id: 52, name: "Jackets", slug: "jackets", parent: "clothing" },
  { id: 53, name: "Suits", slug: "suits", parent: "clothing" },
  { id: 54, name: "Hoodies", slug: "hoodies", parent: "clothing" },
  { id: 55, name: "Sweaters", slug: "sweaters", parent: "clothing" },
  { id: 56, name: "Shorts", slug: "shorts", parent: "clothing" },
  { id: 57, name: "Underwear", slug: "underwear", parent: "clothing" },
  { id: 58, name: "Socks", slug: "socks", parent: "clothing" },
  { id: 59, name: "Sleepwear", slug: "sleepwear", parent: "clothing" },
  { id: 60, name: "Women's Fashion", slug: "womens-fashion", parent: "clothing" },
  { id: 61, name: "Dresses", slug: "dresses", parent: "clothing" },
  { id: 62, name: "Skirts", slug: "skirts", parent: "clothing" },
  { id: 63, name: "Blouses", slug: "blouses", parent: "clothing" },
  { id: 64, name: "Tops", slug: "tops", parent: "clothing" },
  { id: 65, name: "Leggings", slug: "leggings", parent: "clothing" },
  { id: 66, name: "Bras", slug: "bras", parent: "clothing" },
  { id: 67, name: "Panties", slug: "panties", parent: "clothing" },
  { id: 68, name: "Swimwear", slug: "swimwear", parent: "clothing" },
  { id: 69, name: "Maternity Wear", slug: "maternity-wear", parent: "clothing" },
  { id: 70, name: "Plus Size", slug: "plus-size", parent: "clothing" },
  { id: 71, name: "Kids' Fashion", slug: "kids-fashion", parent: "clothing" },
  { id: 72, name: "Baby Clothing", slug: "baby-clothing", parent: "clothing" },
  { id: 73, name: "Toddler Clothing", slug: "toddler-clothing", parent: "clothing" },
  { id: 74, name: "School Uniforms", slug: "school-uniforms", parent: "clothing" },
  { id: 75, name: "Traditional Wear", slug: "traditional-wear", parent: "clothing" },
  { id: 76, name: "Thobes", slug: "thobes", parent: "clothing" },
  { id: 77, name: "Abayas", slug: "abayas", parent: "clothing" },
  { id: 78, name: "Hijabs", slug: "hijabs", parent: "clothing" },
  { id: 79, name: "Kanduras", slug: "kanduras", parent: "clothing" },
  { id: 80, name: "Jilbabs", slug: "jilbabs", parent: "clothing" },
  { id: 81, name: "Accessories", slug: "accessories", parent: null },
  { id: 82, name: "Watches", slug: "watches", parent: "accessories" },
  { id: 83, name: "Luxury Watches", slug: "luxury-watches", parent: "accessories" },
  { id: 84, name: "Smartwatches", slug: "smartwatches", parent: "accessories" },
  { id: 85, name: "Sunglasses", slug: "sunglasses", parent: "accessories" },
  { id: 86, name: "Bags", slug: "bags", parent: "accessories" },
  { id: 87, name: "Backpacks", slug: "backpacks", parent: "accessories" },
  { id: 88, name: "Handbags", slug: "handbags", parent: "accessories" },
  { id: 89, name: "Luggage", slug: "luggage", parent: "accessories" },
  { id: 90, name: "Wallets", slug: "wallets", parent: "accessories" },
  { id: 91, name: "Belts", slug: "belts", parent: "accessories" },
  { id: 92, name: "Hats", slug: "hats", parent: "accessories" },
  { id: 93, name: "Scarves", slug: "scarves", parent: "accessories" },
  { id: 94, name: "Gloves", slug: "gloves", parent: "accessories" },
  { id: 95, name: "Ties", slug: "ties", parent: "accessories" },
  { id: 96, name: "Jewelry", slug: "jewelry", parent: "accessories" },
  { id: 97, name: "Necklaces", slug: "necklaces", parent: "accessories" },
  { id: 98, name: "Rings", slug: "rings", parent: "accessories" },
  { id: 99, name: "Bracelets", slug: "bracelets", parent: "accessories" },
  { id: 100, name: "Earrings", slug: "earrings", parent: "accessories" },
  { id: 101, name: "Gold Jewelry", slug: "gold-jewelry", parent: "accessories" },
  { id: 102, name: "Silver Jewelry", slug: "silver-jewelry", parent: "accessories" },
  { id: 103, name: "Home & Kitchen", slug: "home-kitchen", parent: null },
  { id: 104, name: "Furniture", slug: "furniture", parent: "home-kitchen" },
  { id: 105, name: "Sofas", slug: "sofas", parent: "home-kitchen" },
  { id: 106, name: "Tables", slug: "tables", parent: "home-kitchen" },
  { id: 107, name: "Chairs", slug: "chairs", parent: "home-kitchen" },
  { id: 108, name: "Beds", slug: "beds", parent: "home-kitchen" },
  { id: 109, name: "Cabinets", slug: "cabinets", parent: "home-kitchen" },
  { id: 110, name: "Shelves", slug: "shelves", parent: "home-kitchen" },
  { id: 111, name: "Decor", slug: "decor", parent: "home-kitchen" },
  { id: 112, name: "Lighting", slug: "lighting", parent: "home-kitchen" },
  { id: 113, name: "Curtains", slug: "curtains", parent: "home-kitchen" },
  { id: 114, name: "Rugs", slug: "rugs", parent: "home-kitchen" },
  { id: 115, name: "Cushions", slug: "cushions", parent: "home-kitchen" },
  { id: 116, name: "Wall Art", slug: "wall-art", parent: "home-kitchen" },
  { id: 117, name: "Vases", slug: "vases", parent: "home-kitchen" },
  { id: 118, name: "Fragrances", slug: "fragrances", parent: "home-kitchen" },
  { id: 119, name: "Kitchen Appliances", slug: "kitchen-appliances", parent: "home-kitchen" },
  { id: 120, name: "Refrigerators", slug: "refrigerators", parent: "home-kitchen" },
  { id: 121, name: "Freezers", slug: "freezers", parent: "home-kitchen" },
  { id: 122, name: "Ovens", slug: "ovens", parent: "home-kitchen" },
  { id: 123, name: "Microwaves", slug: "microwaves", parent: "home-kitchen" },
  { id: 124, name: "Blenders", slug: "blenders", parent: "home-kitchen" },
  { id: 125, name: "Mixers", slug: "mixers", parent: "home-kitchen" },
  { id: 126, name: "Coffee Makers", slug: "coffee-makers", parent: "home-kitchen" },
  { id: 127, name: "Air Fryers", slug: "air-fryers", parent: "home-kitchen" },
  { id: 128, name: "Rice Cookers", slug: "rice-cookers", parent: "home-kitchen" },
  { id: 129, name: "Cookware", slug: "cookware", parent: "home-kitchen" },
  { id: 130, name: "Pots & Pans", slug: "pots-pans", parent: "home-kitchen" },
  { id: 131, name: "Bakeware", slug: "bakeware", parent: "home-kitchen" },
  { id: 132, name: "Cutlery", slug: "cutlery", parent: "home-kitchen" },
  { id: 133, name: "Kitchen Tools", slug: "kitchen-tools", parent: "home-kitchen" },
  { id: 134, name: "Tableware", slug: "tableware", parent: "home-kitchen" },
  { id: 135, name: "Dinner Sets", slug: "dinner-sets", parent: "home-kitchen" },
  { id: 136, name: "Glassware", slug: "glassware", parent: "home-kitchen" },
  { id: 137, name: "Drinkware", slug: "drinkware", parent: "home-kitchen" },
  { id: 138, name: "Cleaning Supplies", slug: "cleaning-supplies", parent: "home-kitchen" },
  { id: 139, name: "Laundry", slug: "laundry", parent: "home-kitchen" },
  { id: 140, name: "Storage & Organization", slug: "storage-organization", parent: "home-kitchen" },
  { id: 141, name: "Bedding", slug: "bedding", parent: "home-kitchen" },
  { id: 142, name: "Towels", slug: "towels", parent: "home-kitchen" },
  { id: 143, name: "Beauty & Health", slug: "beauty-health", parent: null },
  { id: 144, name: "Skincare", slug: "skincare", parent: "beauty-health" },
  { id: 145, name: "Face Creams", slug: "face-creams", parent: "beauty-health" },
  { id: 146, name: "Serums", slug: "serums", parent: "beauty-health" },
  { id: 147, name: "Sunscreens", slug: "sunscreens", parent: "beauty-health" },
  { id: 148, name: "Cleansers", slug: "cleansers", parent: "beauty-health" },
  { id: 149, name: "Toners", slug: "toners", parent: "beauty-health" },
  { id: 150, name: "Moisturizers", slug: "moisturizers", parent: "beauty-health" },
  { id: 151, name: "Makeup", slug: "makeup", parent: "beauty-health" },
  { id: 152, name: "Foundation", slug: "foundation", parent: "beauty-health" },
  { id: 153, name: "Lipstick", slug: "lipstick", parent: "beauty-health" },
  { id: 154, name: "Mascara", slug: "mascara", parent: "beauty-health" },
  { id: 155, name: "Eyeliner", slug: "eyeliner", parent: "beauty-health" },
  { id: 156, name: "Blush", slug: "blush", parent: "beauty-health" },
  { id: 157, name: "Makeup Brushes", slug: "makeup-brushes", parent: "beauty-health" },
  { id: 158, name: "Hair Care", slug: "hair-care", parent: "beauty-health" },
  { id: 159, name: "Shampoos", slug: "shampoos", parent: "beauty-health" },
  { id: 160, name: "Conditioners", slug: "conditioners", parent: "beauty-health" },
  { id: 161, name: "Hair Oils", slug: "hair-oils", parent: "beauty-health" },
  { id: 162, name: "Hair Styling", slug: "hair-styling", parent: "beauty-health" },
  { id: 163, name: "Hair Color", slug: "hair-color", parent: "beauty-health" },
  { id: 164, name: "Perfumes", slug: "perfumes", parent: "beauty-health" },
  { id: 165, name: "Men's Perfumes", slug: "mens-perfumes", parent: "beauty-health" },
  { id: 166, name: "Women's Perfumes", slug: "womens-perfumes", parent: "beauty-health" },
  { id: 167, name: "Body Care", slug: "body-care", parent: "beauty-health" },
  { id: 168, name: "Shower Gels", slug: "shower-gels", parent: "beauty-health" },
  { id: 169, name: "Body Lotions", slug: "body-lotions", parent: "beauty-health" },
  { id: 170, name: "Deodorants", slug: "deodorants", parent: "beauty-health" },
  { id: 171, name: "Nail Care", slug: "nail-care", parent: "beauty-health" },
  { id: 172, name: "Nail Polish", slug: "nail-polish", parent: "beauty-health" },
  { id: 173, name: "Oral Care", slug: "oral-care", parent: "beauty-health" },
  { id: 174, name: "Shaving", slug: "shaving", parent: "beauty-health" },
  { id: 175, name: "Beauty Tools", slug: "beauty-tools", parent: "beauty-health" },
  { id: 176, name: "Vitamins", slug: "vitamins", parent: "beauty-health" },
  { id: 177, name: "Supplements", slug: "supplements", parent: "beauty-health" },
  { id: 178, name: "Medical Supplies", slug: "medical-supplies", parent: "beauty-health" },
  { id: 179, name: "Personal Care", slug: "personal-care", parent: "beauty-health" },
  { id: 180, name: "Sports & Outdoors", slug: "sports-outdoors", parent: null },
  { id: 181, name: "Fitness Equipment", slug: "fitness-equipment", parent: "sports-outdoors" },
  { id: 182, name: "Treadmills", slug: "treadmills", parent: "sports-outdoors" },
  { id: 183, name: "Exercise Bikes", slug: "exercise-bikes", parent: "sports-outdoors" },
  { id: 184, name: "Dumbbells", slug: "dumbbells", parent: "sports-outdoors" },
  { id: 185, name: "Yoga Mats", slug: "yoga-mats", parent: "sports-outdoors" },
  { id: 186, name: "Resistance Bands", slug: "resistance-bands", parent: "sports-outdoors" },
  { id: 187, name: "Sports Clothing", slug: "sports-clothing", parent: "sports-outdoors" },
  { id: 188, name: "Sports Shoes", slug: "sports-shoes", parent: "sports-outdoors" },
  { id: 189, name: "Running Shoes", slug: "running-shoes", parent: "sports-outdoors" },
  { id: 190, name: "Football Boots", slug: "football-boots", parent: "sports-outdoors" },
  { id: 191, name: "Basketball Shoes", slug: "basketball-shoes", parent: "sports-outdoors" },
  { id: 192, name: "Training Shoes", slug: "training-shoes", parent: "sports-outdoors" },
  { id: 193, name: "Outdoor Recreation", slug: "outdoor-recreation", parent: "sports-outdoors" },
  { id: 194, name: "Camping", slug: "camping", parent: "sports-outdoors" },
  { id: 195, name: "Hiking", slug: "hiking", parent: "sports-outdoors" },
  { id: 196, name: "Fishing", slug: "fishing", parent: "sports-outdoors" },
  { id: 197, name: "Cycling", slug: "cycling", parent: "sports-outdoors" },
  { id: 198, name: "Swimming", slug: "swimming", parent: "sports-outdoors" },
  { id: 199, name: "Team Sports", slug: "team-sports", parent: "sports-outdoors" },
  { id: 200, name: "Football", slug: "football", parent: "sports-outdoors" },
  { id: 201, name: "Basketball", slug: "basketball", parent: "sports-outdoors" },
  { id: 202, name: "Tennis", slug: "tennis", parent: "sports-outdoors" },
  { id: 203, name: "Volleyball", slug: "volleyball", parent: "sports-outdoors" },
  { id: 204, name: "Boxing", slug: "boxing", parent: "sports-outdoors" },
  { id: 205, name: "Martial Arts", slug: "martial-arts", parent: "sports-outdoors" },
  { id: 206, name: "Toys & Games", slug: "toys-games", parent: null },
  { id: 207, name: "Action Figures", slug: "action-figures", parent: "toys-games" },
  { id: 208, name: "Dolls", slug: "dolls", parent: "toys-games" },
  { id: 209, name: "Board Games", slug: "board-games", parent: "toys-games" },
  { id: 210, name: "Puzzles", slug: "puzzles", parent: "toys-games" },
  { id: 211, name: "Building Blocks", slug: "building-blocks", parent: "toys-games" },
  { id: 212, name: "Remote Control", slug: "remote-control", parent: "toys-games" },
  { id: 213, name: "Educational Toys", slug: "educational-toys", parent: "toys-games" },
  { id: 214, name: "Outdoor Toys", slug: "outdoor-toys", parent: "toys-games" },
  { id: 215, name: "Video Games", slug: "video-games", parent: "toys-games" },
  { id: 216, name: "PlayStation Games", slug: "playstation-games", parent: "toys-games" },
  { id: 217, name: "Xbox Games", slug: "xbox-games", parent: "toys-games" },
  { id: 218, name: "PC Games", slug: "pc-games", parent: "toys-games" },
  { id: 219, name: "Nintendo Games", slug: "nintendo-games", parent: "toys-games" },
  { id: 220, name: "Stuffed Toys", slug: "stuffed-toys", parent: "toys-games" },
  { id: 221, name: "Arts & Crafts", slug: "arts-crafts", parent: "toys-games" },
  { id: 222, name: "Books", slug: "books", parent: null },
  { id: 223, name: "Arabic Books", slug: "arabic-books", parent: "books" },
  { id: 224, name: "English Books", slug: "english-books", parent: "books" },
  { id: 225, name: "Educational Books", slug: "educational-books", parent: "books" },
  { id: 226, name: "Children's Books", slug: "childrens-books", parent: "books" },
  { id: 227, name: "Islamic Books", slug: "islamic-books", parent: "books" },
  { id: 228, name: "Novels", slug: "novels", parent: "books" },
  { id: 229, name: "Self-Help Books", slug: "self-help-books", parent: "books" },
  { id: 230, name: "Cookbooks", slug: "cookbooks", parent: "books" },
  { id: 231, name: "Stationery", slug: "stationery", parent: "books" },
  { id: 232, name: "Notebooks", slug: "notebooks", parent: "books" },
  { id: 233, name: "Pens", slug: "pens", parent: "books" },
  { id: 234, name: "Office Supplies", slug: "office-supplies", parent: "books" },
  { id: 235, name: "Art Supplies", slug: "art-supplies", parent: "books" },
  { id: 236, name: "Auto Parts", slug: "auto-parts", parent: null },
  { id: 237, name: "Car Accessories", slug: "car-accessories", parent: "auto-parts" },
  { id: 238, name: "Car Electronics", slug: "car-electronics", parent: "auto-parts" },
  { id: 239, name: "Car Care", slug: "car-care", parent: "auto-parts" },
  { id: 240, name: "Tires", slug: "tires", parent: "auto-parts" },
  { id: 241, name: "Oils & Fluids", slug: "oils-fluids", parent: "auto-parts" },
  { id: 242, name: "Motorcycle Parts", slug: "motorcycle-parts", parent: "auto-parts" },
  { id: 243, name: "Baby & Kids", slug: "baby-kids", parent: null },
  { id: 244, name: "Diapers", slug: "diapers", parent: "baby-kids" },
  { id: 245, name: "Baby Wipes", slug: "baby-wipes", parent: "baby-kids" },
  { id: 246, name: "Baby Formula", slug: "baby-formula", parent: "baby-kids" },
  { id: 247, name: "Baby Feeding", slug: "baby-feeding", parent: "baby-kids" },
  { id: 248, name: "Baby Bath", slug: "baby-bath", parent: "baby-kids" },
  { id: 249, name: "Baby Gear", slug: "baby-gear", parent: "baby-kids" },
  { id: 250, name: "Strollers", slug: "strollers", parent: "baby-kids" },
  { id: 251, name: "Car Seats", slug: "car-seats", parent: "baby-kids" },
  { id: 252, name: "Baby Toys", slug: "baby-toys", parent: "baby-kids" },
  { id: 253, name: "Nursery", slug: "nursery", parent: "baby-kids" },
  { id: 254, name: "Pet Supplies", slug: "pet-supplies", parent: null },
  { id: 255, name: "Dog Food", slug: "dog-food", parent: "pet-supplies" },
  { id: 256, name: "Cat Food", slug: "cat-food", parent: "pet-supplies" },
  { id: 257, name: "Pet Toys", slug: "pet-toys", parent: "pet-supplies" },
  { id: 258, name: "Pet Accessories", slug: "pet-accessories", parent: "pet-supplies" },
  { id: 259, name: "Pet Health", slug: "pet-health", parent: "pet-supplies" },
  { id: 260, name: "Aquarium", slug: "aquarium", parent: "pet-supplies" },
  { id: 261, name: "Groceries", slug: "groceries", parent: null },
  { id: 262, name: "Rice", slug: "rice", parent: "groceries" },
  { id: 263, name: "Cooking Oil", slug: "cooking-oil", parent: "groceries" },
  { id: 264, name: "Sugar", slug: "sugar", parent: "groceries" },
  { id: 265, name: "Flour", slug: "flour", parent: "groceries" },
  { id: 266, name: "Spices", slug: "spices", parent: "groceries" },
  { id: 267, name: "Canned Food", slug: "canned-food", parent: "groceries" },
  { id: 268, name: "Beverages", slug: "beverages", parent: "groceries" },
  { id: 269, name: "Water", slug: "water", parent: "groceries" },
  { id: 270, name: "Juices", slug: "juices", parent: "groceries" },
  { id: 271, name: "Soft Drinks", slug: "soft-drinks", parent: "groceries" },
  { id: 272, name: "Coffee", slug: "coffee", parent: "groceries" },
  { id: 273, name: "Tea", slug: "tea", parent: "groceries" },
  { id: 274, name: "Snacks", slug: "snacks", parent: "groceries" },
  { id: 275, name: "Chocolate", slug: "chocolate", parent: "groceries" },
  { id: 276, name: "Chips", slug: "chips", parent: "groceries" },
  { id: 277, name: "Nuts", slug: "nuts", parent: "groceries" },
  { id: 278, name: "Dates", slug: "dates", parent: "groceries" },
  { id: 279, name: "Honey", slug: "honey", parent: "groceries" },
  { id: 280, name: "Dairy", slug: "dairy", parent: "groceries" },
  { id: 281, name: "Milk", slug: "milk", parent: "groceries" },
  { id: 282, name: "Yogurt", slug: "yogurt", parent: "groceries" },
  { id: 283, name: "Cheese", slug: "cheese", parent: "groceries" },
  { id: 284, name: "Eggs", slug: "eggs", parent: "groceries" },
  { id: 285, name: "Frozen Food", slug: "frozen-food", parent: "groceries" },
  { id: 286, name: "Fruits", slug: "fruits", parent: "groceries" },
  { id: 287, name: "Vegetables", slug: "vegetables", parent: "groceries" },
  { id: 288, name: "Meat", slug: "meat", parent: "groceries" },
  { id: 289, name: "Chicken", slug: "chicken", parent: "groceries" },
  { id: 290, name: "Fish", slug: "fish", parent: "groceries" },
  { id: 291, name: "Bread", slug: "bread", parent: "groceries" },
  { id: 292, name: "Sauces", slug: "sauces", parent: "groceries" },
  { id: 293, name: "Health & Household", slug: "health-household", parent: null },
  { id: 294, name: "Cleaning", slug: "cleaning", parent: "health-household" },
  { id: 295, name: "Laundry Detergent", slug: "laundry-detergent", parent: "health-household" },
  { id: 296, name: "Dish Soap", slug: "dish-soap", parent: "health-household" },
  { id: 297, name: "Air Fresheners", slug: "air-fresheners", parent: "health-household" },
  { id: 298, name: "Toilet Paper", slug: "toilet-paper", parent: "health-household" },
  { id: 299, name: "Paper Towels", slug: "paper-towels", parent: "health-household" },
  { id: 300, name: "Tissues", slug: "tissues", parent: "health-household" },
  { id: 301, name: "Trash Bags", slug: "trash-bags", parent: "health-household" },
  { id: 302, name: "Insect Repellent", slug: "insect-repellent", parent: "health-household" },
  { id: 303, name: "Hand Sanitizer", slug: "hand-sanitizer", parent: "health-household" },
  { id: 304, name: "Face Masks", slug: "face-masks", parent: "health-household" },
  { id: 305, name: "First Aid", slug: "first-aid", parent: "health-household" },
  { id: 306, name: "Batteries", slug: "batteries", parent: "health-household" },
  { id: 307, name: "Light Bulbs", slug: "light-bulbs", parent: "health-household" },
  { id: 308, name: "Tools & Hardware", slug: "tools-hardware", parent: null },
  { id: 309, name: "Power Tools", slug: "power-tools", parent: "tools-hardware" },
  { id: 310, name: "Hand Tools", slug: "hand-tools", parent: "tools-hardware" },
  { id: 311, name: "Gardening", slug: "gardening", parent: "tools-hardware" },
  { id: 312, name: "Electrical", slug: "electrical", parent: "tools-hardware" },
  { id: 313, name: "Plumbing", slug: "plumbing", parent: "tools-hardware" },
  { id: 314, name: "Hardware", slug: "hardware", parent: "tools-hardware" },
  { id: 315, name: "Safety", slug: "safety", parent: "tools-hardware" },
  { id: 316, name: "Musical Instruments", slug: "musical-instruments", parent: null },
  { id: 317, name: "Guitars", slug: "guitars", parent: "musical-instruments" },
  { id: 318, name: "Keyboards", slug: "keyboards", parent: "musical-instruments" },
  { id: 319, name: "Drums", slug: "drums", parent: "musical-instruments" },
  { id: 320, name: "Audio Equipment", slug: "audio-equipment", parent: "musical-instruments" },
  { id: 321, name: "Microphones", slug: "microphones", parent: "musical-instruments" },
  { id: 322, name: "Office Products", slug: "office-products", parent: null },
  { id: 323, name: "Office Furniture", slug: "office-furniture", parent: "office-products" },
  { id: 324, name: "Office Electronics", slug: "office-electronics", parent: "office-products" },
  { id: 325, name: "Printers & Scanners", slug: "printers-scanners", parent: "office-products" },
  { id: 326, name: "Projectors", slug: "projectors", parent: "office-products" },
  { id: 327, name: "Phone Accessories", slug: "phone-accessories", parent: "office-products" },
  { id: 328, name: "Screen Protectors", slug: "screen-protectors", parent: "office-products" },
  { id: 329, name: "Phone Cases", slug: "phone-cases", parent: "office-products" },
  { id: 330, name: "Car Phone Mounts", slug: "car-phone-mounts", parent: "office-products" },
  { id: 331, name: "Selfie Sticks", slug: "selfie-sticks", parent: "office-products" },
  { id: 332, name: "Tripods", slug: "tripods", parent: "office-products" },
  { id: 333, name: "Food & Beverage", slug: "food-beverage", parent: null },
  { id: 334, name: "Coffee & Tea", slug: "coffee-tea", parent: "food-beverage" },
  { id: 335, name: "Energy Drinks", slug: "energy-drinks", parent: "food-beverage" },
  { id: 336, name: "Health Drinks", slug: "health-drinks", parent: "food-beverage" },
  { id: 337, name: "Organic Food", slug: "organic-food", parent: "food-beverage" },
  { id: 338, name: "Halal Food", slug: "halal-food", parent: "food-beverage" },
  { id: 339, name: "Electronics Accessories", slug: "electronics-accessories", parent: null },
  { id: 340, name: "USB Hubs", slug: "usb-hubs", parent: "electronics-accessories" },
  { id: 341, name: "HDMI Cables", slug: "hdmi-cables", parent: "electronics-accessories" },
  { id: 342, name: "Memory Cards", slug: "memory-cards", parent: "electronics-accessories" },
  { id: 343, name: "USB Drives", slug: "usb-drives", parent: "electronics-accessories" },
  { id: 344, name: "Hard Drives", slug: "hard-drives", parent: "electronics-accessories" },
  { id: 345, name: "SSDs", slug: "ssds", parent: "electronics-accessories" },
  { id: 346, name: "Mouse Pads", slug: "mouse-pads", parent: "electronics-accessories" },
  { id: 347, name: "Keyboard Covers", slug: "keyboard-covers", parent: "electronics-accessories" },
  { id: 348, name: "Laptop Stands", slug: "laptop-stands", parent: "electronics-accessories" },
  { id: 349, name: "Laptop Bags", slug: "laptop-bags", parent: "electronics-accessories" },
  { id: 350, name: "Screen Cleaners", slug: "screen-cleaners", parent: "electronics-accessories" },
  { id: 351, name: "Cable Organizers", slug: "cable-organizers", parent: "electronics-accessories" },
  { id: 352, name: "Phone Stands", slug: "phone-stands", parent: "electronics-accessories" },
  { id: 353, name: "Wireless Chargers", slug: "wireless-chargers", parent: "electronics-accessories" },
  { id: 354, name: "Gaming Gear", slug: "gaming-gear", parent: null },
  { id: 355, name: "Gaming Mice", slug: "gaming-mice", parent: "gaming-gear" },
  { id: 356, name: "Gaming Keyboards", slug: "gaming-keyboards", parent: "gaming-gear" },
  { id: 357, name: "Gaming Headsets", slug: "gaming-headsets", parent: "gaming-gear" },
  { id: 358, name: "Gaming Chairs", slug: "gaming-chairs", parent: "gaming-gear" },
  { id: 359, name: "Gaming Desks", slug: "gaming-desks", parent: "gaming-gear" },
  { id: 360, name: "Streaming", slug: "streaming", parent: "gaming-gear" },
  { id: 361, name: "Capture Cards", slug: "capture-cards", parent: "gaming-gear" },
  { id: 362, name: "Gaming Controllers", slug: "gaming-controllers", parent: "gaming-gear" },
  { id: 363, name: "VR Accessories", slug: "vr-accessories", parent: "gaming-gear" },
  { id: 364, name: "Miscellaneous", slug: "misc", parent: null },
  { id: 365, name: "Clearance", slug: "clearance", parent: "misc" },
  { id: 366, name: "Trending Products", slug: "trending-products", parent: "misc" },
  { id: 367, name: "Seasonal Items", slug: "seasonal-items", parent: "misc" },
  { id: 368, name: "Gift Ideas", slug: "gift-ideas", parent: "misc" },
  { id: 369, name: "New Arrivals", slug: "new-arrivals", parent: "misc" },
  { id: 370, name: "Limited Edition", slug: "limited-edition", parent: "misc" },
  { id: 371, name: "Flash Sale", slug: "flash-sale", parent: "misc" },
  { id: 372, name: "Bundles", slug: "bundles", parent: "misc" },
  { id: 373, name: "Refurbished", slug: "refurbished", parent: "misc" },
];

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
