import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  { id: 1, name: "Electronics", slug: "electronics", parent: null },
  { id: 2, name: "Smartphones", slug: "smartphones", parent: "electronics" },
  { id: 3, name: "Android Phones", slug: "android-phones", parent: "electronics" },
  { id: 4, name: "iPhones", slug: "iphones", parent: "electronics" },
  { id: 5, name: "Tablets", slug: "tablets", parent: "electronics" },
  { id: 6, name: "Laptops", slug: "laptops", parent: "electronics" },
  { id: 7, name: "Gaming Laptops", slug: "gaming-laptops", parent: "electronics" },
  { id: 8, name: "Desktop PCs", slug: "desktop-pcs", parent: "electronics" },
  { id: 9, name: "Monitors", slug: "monitors", parent: "electronics" },
  { id: 10, name: "Gaming Monitors", slug: "gaming-monitors", parent: "electronics" },
  { id: 11, name: "Cameras", slug: "cameras", parent: "electronics" },
  { id: 12, name: "DSLR Cameras", slug: "dslr-cameras", parent: "electronics" },
  { id: 13, name: "Action Cameras", slug: "action-cameras", parent: "electronics" },
  { id: 14, name: "Security Cameras", slug: "security-cameras", parent: "electronics" },
  { id: 15, name: "Smart Watches", slug: "smart-watches", parent: "electronics" },
  { id: 16, name: "Fitness Bands", slug: "fitness-bands", parent: "electronics" },
  { id: 17, name: "Headphones", slug: "headphones", parent: "electronics" },
  { id: 18, name: "Earbuds", slug: "earbuds", parent: "electronics" },
  { id: 19, name: "Speakers", slug: "speakers", parent: "electronics" },
  { id: 20, name: "Bluetooth Speakers", slug: "bluetooth-speakers", parent: "electronics" },
  { id: 21, name: "Gaming Consoles", slug: "gaming-consoles", parent: "electronics" },
  { id: 22, name: "PlayStation", slug: "playstation", parent: "electronics" },
  { id: 23, name: "Xbox", slug: "xbox", parent: "electronics" },
  { id: 24, name: "Nintendo", slug: "nintendo", parent: "electronics" },
  { id: 25, name: "Computer Accessories", slug: "computer-accessories", parent: "electronics" },
  { id: 26, name: "Mobile Accessories", slug: "mobile-accessories", parent: "electronics" },
  { id: 27, name: "Chargers", slug: "chargers", parent: "electronics" },
  { id: 28, name: "Power Banks", slug: "power-banks", parent: "electronics" },
  { id: 29, name: "Cables", slug: "cables", parent: "electronics" },
  { id: 30, name: "Routers", slug: "routers", parent: "electronics" },
  { id: 31, name: "Smart Home", slug: "smart-home", parent: "electronics" },
  { id: 32, name: "TVs", slug: "tvs", parent: "electronics" },
  { id: 33, name: "Projectors", slug: "projectors", parent: "electronics" },
  { id: 34, name: "Drones", slug: "drones", parent: "electronics" },
  { id: 35, name: "Printers", slug: "printers", parent: "electronics" },
  { id: 36, name: "VR Devices", slug: "vr-devices", parent: "electronics" },
  { id: 37, name: "Graphic Cards", slug: "graphic-cards", parent: "electronics" },
  { id: 38, name: "Processors", slug: "processors", parent: "electronics" },
  { id: 39, name: "Storage Devices", slug: "storage-devices", parent: "electronics" },
  { id: 40, name: "Motherboards", slug: "motherboards", parent: "electronics" },
  { id: 41, name: "Cooling Fans", slug: "cooling-fans", parent: "electronics" },
  { id: 42, name: "Networking Devices", slug: "networking-devices", parent: "electronics" },
  { id: 43, name: "Car Electronics", slug: "car-electronics", parent: "electronics" },
  { id: 44, name: "Audio Systems", slug: "audio-systems", parent: "electronics" },
  { id: 45, name: "Smart Devices", slug: "smart-devices", parent: "electronics" },
  { id: 46, name: "Fashion", slug: "fashion", parent: null },
  { id: 47, name: "Men Clothing", slug: "men-clothing", parent: "fashion" },
  { id: 48, name: "Women Clothing", slug: "women-clothing", parent: "fashion" },
  { id: 49, name: "Kids Clothing", slug: "kids-clothing", parent: "fashion" },
  { id: 50, name: "T-Shirts", slug: "t-shirts", parent: "fashion" },
  { id: 51, name: "Shirts", slug: "shirts", parent: "fashion" },
  { id: 52, name: "Jeans", slug: "jeans", parent: "fashion" },
  { id: 53, name: "Jackets", slug: "jackets", parent: "fashion" },
  { id: 54, name: "Coats", slug: "coats", parent: "fashion" },
  { id: 55, name: "Shoes", slug: "shoes", parent: "fashion" },
  { id: 56, name: "Sneakers", slug: "sneakers", parent: "fashion" },
  { id: 57, name: "Formal Shoes", slug: "formal-shoes", parent: "fashion" },
  { id: 58, name: "Sandals", slug: "sandals", parent: "fashion" },
  { id: 59, name: "Bags", slug: "bags", parent: "fashion" },
  { id: 60, name: "Handbags", slug: "handbags", parent: "fashion" },
  { id: 61, name: "Backpacks", slug: "backpacks", parent: "fashion" },
  { id: 62, name: "Watches", slug: "watches", parent: "fashion" },
  { id: 63, name: "Jewelry", slug: "jewelry", parent: "fashion" },
  { id: 64, name: "Sunglasses", slug: "sunglasses", parent: "fashion" },
  { id: 65, name: "Sportswear", slug: "sportswear", parent: "fashion" },
  { id: 66, name: "Underwear", slug: "underwear", parent: "fashion" },
  { id: 67, name: "Hats", slug: "hats", parent: "fashion" },
  { id: 68, name: "Belts", slug: "belts", parent: "fashion" },
  { id: 69, name: "Socks", slug: "socks", parent: "fashion" },
  { id: 70, name: "Traditional Wear", slug: "traditional-wear", parent: "fashion" },
  { id: 71, name: "Luxury Fashion", slug: "luxury-fashion", parent: "fashion" },
  { id: 72, name: "Swimwear", slug: "swimwear", parent: "fashion" },
  { id: 73, name: "Dresses", slug: "dresses", parent: "fashion" },
  { id: 74, name: "Skirts", slug: "skirts", parent: "fashion" },
  { id: 75, name: "Hoodies", slug: "hoodies", parent: "fashion" },
  { id: 76, name: "Tracksuits", slug: "tracksuits", parent: "fashion" },
  { id: 77, name: "Sports Shoes", slug: "sports-shoes", parent: "fashion" },
  { id: 78, name: "Accessories", slug: "accessories", parent: "fashion" },
  { id: 79, name: "Wallets", slug: "wallets", parent: "fashion" },
  { id: 80, name: "Perfume Fashion", slug: "perfume-fashion", parent: "fashion" },
  { id: 81, name: "Home & Kitchen", slug: "home-kitchen", parent: null },
  { id: 82, name: "Furniture", slug: "furniture", parent: "home-kitchen" },
  { id: 83, name: "Bedroom Furniture", slug: "bedroom-furniture", parent: "home-kitchen" },
  { id: 84, name: "Living Room Furniture", slug: "living-room-furniture", parent: "home-kitchen" },
  { id: 85, name: "Kitchen Appliances", slug: "kitchen-appliances", parent: "home-kitchen" },
  { id: 86, name: "Cookware", slug: "cookware", parent: "home-kitchen" },
  { id: 87, name: "Utensils", slug: "utensils", parent: "home-kitchen" },
  { id: 88, name: "Lighting", slug: "lighting", parent: "home-kitchen" },
  { id: 89, name: "LED Lights", slug: "led-lights", parent: "home-kitchen" },
  { id: 90, name: "Curtains", slug: "curtains", parent: "home-kitchen" },
  { id: 91, name: "Carpets", slug: "carpets", parent: "home-kitchen" },
  { id: 92, name: "Storage", slug: "storage", parent: "home-kitchen" },
  { id: 93, name: "Cleaning Tools", slug: "cleaning-tools", parent: "home-kitchen" },
  { id: 94, name: "Bathroom Items", slug: "bathroom-items", parent: "home-kitchen" },
  { id: 95, name: "Mattresses", slug: "mattresses", parent: "home-kitchen" },
  { id: 96, name: "Beds", slug: "beds", parent: "home-kitchen" },
  { id: 97, name: "Tables", slug: "tables", parent: "home-kitchen" },
  { id: 98, name: "Chairs", slug: "chairs", parent: "home-kitchen" },
  { id: 99, name: "Kitchen Storage", slug: "kitchen-storage", parent: "home-kitchen" },
  { id: 100, name: "Decor Items", slug: "decor-items", parent: "home-kitchen" },
  { id: 101, name: "Wall Art", slug: "wall-art", parent: "home-kitchen" },
  { id: 102, name: "Clocks", slug: "clocks", parent: "home-kitchen" },
  { id: 103, name: "Mirrors", slug: "mirrors", parent: "home-kitchen" },
  { id: 104, name: "Gardening Tools", slug: "gardening-tools", parent: "home-kitchen" },
  { id: 105, name: "Outdoor Furniture", slug: "outdoor-furniture", parent: "home-kitchen" },
  { id: 106, name: "Blenders", slug: "blenders", parent: "home-kitchen" },
  { id: 107, name: "Coffee Machines", slug: "coffee-machines", parent: "home-kitchen" },
  { id: 108, name: "Air Fryers", slug: "air-fryers", parent: "home-kitchen" },
  { id: 109, name: "Vacuum Cleaners", slug: "vacuum-cleaners", parent: "home-kitchen" },
  { id: 110, name: "Ironing Tools", slug: "ironing-tools", parent: "home-kitchen" },
  { id: 111, name: "Dish Racks", slug: "dish-racks", parent: "home-kitchen" },
  { id: 112, name: "Water Filters", slug: "water-filters", parent: "home-kitchen" },
  { id: 113, name: "Fans", slug: "fans", parent: "home-kitchen" },
  { id: 114, name: "Heaters", slug: "heaters", parent: "home-kitchen" },
  { id: 115, name: "Kitchen Knives", slug: "kitchen-knives", parent: "home-kitchen" },
  { id: 116, name: "Beauty", slug: "beauty", parent: null },
  { id: 117, name: "Skincare", slug: "skincare", parent: "beauty" },
  { id: 118, name: "Haircare", slug: "haircare", parent: "beauty" },
  { id: 119, name: "Makeup", slug: "makeup", parent: "beauty" },
  { id: 120, name: "Perfumes", slug: "perfumes", parent: "beauty" },
  { id: 121, name: "Body Care", slug: "body-care", parent: "beauty" },
  { id: 122, name: "Beauty Devices", slug: "beauty-devices", parent: "beauty" },
  { id: 123, name: "Men Grooming", slug: "men-grooming", parent: "beauty" },
  { id: 124, name: "Lipsticks", slug: "lipsticks", parent: "beauty" },
  { id: 125, name: "Foundation", slug: "foundation", parent: "beauty" },
  { id: 126, name: "Shampoo", slug: "shampoo", parent: "beauty" },
  { id: 127, name: "Conditioner", slug: "conditioner", parent: "beauty" },
  { id: 128, name: "Face Creams", slug: "face-creams", parent: "beauty" },
  { id: 129, name: "Serums", slug: "serums", parent: "beauty" },
  { id: 130, name: "Eye Care", slug: "eye-care", parent: "beauty" },
  { id: 131, name: "Nail Care", slug: "nail-care", parent: "beauty" },
  { id: 132, name: "Makeup Brushes", slug: "makeup-brushes", parent: "beauty" },
  { id: 133, name: "Hair Styling Tools", slug: "hair-styling-tools", parent: "beauty" },
  { id: 134, name: "Hair Oil", slug: "hair-oil", parent: "beauty" },
  { id: 135, name: "Face Wash", slug: "face-wash", parent: "beauty" },
  { id: 136, name: "Deodorants", slug: "deodorants", parent: "beauty" },
  { id: 137, name: "Baby & Kids", slug: "baby-kids", parent: null },
  { id: 138, name: "Baby Clothing", slug: "baby-clothing", parent: "baby-kids" },
  { id: 139, name: "Toys", slug: "toys", parent: "baby-kids" },
  { id: 140, name: "Baby Care", slug: "baby-care", parent: "baby-kids" },
  { id: 141, name: "Strollers", slug: "strollers", parent: "baby-kids" },
  { id: 142, name: "Feeding Items", slug: "feeding-items", parent: "baby-kids" },
  { id: 143, name: "Diapers", slug: "diapers", parent: "baby-kids" },
  { id: 144, name: "Baby Beds", slug: "baby-beds", parent: "baby-kids" },
  { id: 145, name: "Kids Toys", slug: "kids-toys", parent: "baby-kids" },
  { id: 146, name: "Educational Toys", slug: "educational-toys", parent: "baby-kids" },
  { id: 147, name: "Baby Safety", slug: "baby-safety", parent: "baby-kids" },
  { id: 148, name: "Baby Food", slug: "baby-food", parent: "baby-kids" },
  { id: 149, name: "Kids Clothing", slug: "kids-clothing", parent: "baby-kids" },
  { id: 150, name: "Kids Shoes", slug: "kids-shoes", parent: "baby-kids" },
  { id: 151, name: "Baby Accessories", slug: "baby-accessories", parent: "baby-kids" },
  { id: 152, name: "Baby Bath", slug: "baby-bath", parent: "baby-kids" },
  { id: 153, name: "Sports & Outdoors", slug: "sports", parent: null },
  { id: 154, name: "Fitness Equipment", slug: "fitness-equipment", parent: "sports" },
  { id: 155, name: "Gym Accessories", slug: "gym-accessories", parent: "sports" },
  { id: 156, name: "Dumbbells", slug: "dumbbells", parent: "sports" },
  { id: 157, name: "Yoga Mats", slug: "yoga-mats", parent: "sports" },
  { id: 158, name: "Camping", slug: "camping", parent: "sports" },
  { id: 159, name: "Cycling", slug: "cycling", parent: "sports" },
  { id: 160, name: "Football", slug: "football", parent: "sports" },
  { id: 161, name: "Basketball", slug: "basketball", parent: "sports" },
  { id: 162, name: "Swimming", slug: "swimming", parent: "sports" },
  { id: 163, name: "Tennis", slug: "tennis", parent: "sports" },
  { id: 164, name: "Running Gear", slug: "running-gear", parent: "sports" },
  { id: 165, name: "Outdoor Gear", slug: "outdoor-gear", parent: "sports" },
  { id: 166, name: "Fishing", slug: "fishing", parent: "sports" },
  { id: 167, name: "Hiking", slug: "hiking", parent: "sports" },
  { id: 168, name: "Skating", slug: "skating", parent: "sports" },
  { id: 169, name: "Climbing", slug: "climbing", parent: "sports" },
  { id: 170, name: "Sports Wear", slug: "sports-wear", parent: "sports" },
  { id: 171, name: "Sports Shoes", slug: "sports-shoes", parent: "sports" },
  { id: 172, name: "Training Equipment", slug: "training-equipment", parent: "sports" },
  { id: 173, name: "Protein Supplements", slug: "protein-supplements", parent: "sports" },
  { id: 174, name: "Bikes", slug: "bikes", parent: "sports" },
  { id: 175, name: "Exercise Machines", slug: "exercise-machines", parent: "sports" },
  { id: 176, name: "Treadmills", slug: "treadmills", parent: "sports" },
  { id: 177, name: "Home Gym", slug: "home-gym", parent: "sports" },
  { id: 178, name: "Boxing Gear", slug: "boxing-gear", parent: "sports" },
  { id: 179, name: "Martial Arts", slug: "martial-arts", parent: "sports" },
  { id: 180, name: "Water Sports", slug: "water-sports", parent: "sports" },
  { id: 181, name: "Winter Sports", slug: "winter-sports", parent: "sports" },
  { id: 182, name: "Team Sports", slug: "team-sports", parent: "sports" },
  { id: 183, name: "Adventure Gear", slug: "adventure-gear", parent: "sports" },
  { id: 184, name: "Automotive", slug: "automotive", parent: null },
  { id: 185, name: "Car Accessories", slug: "car-accessories", parent: "automotive" },
  { id: 186, name: "Car Electronics", slug: "car-electronics", parent: "automotive" },
  { id: 187, name: "Oils & Fluids", slug: "oils-&-fluids", parent: "automotive" },
  { id: 188, name: "Tires", slug: "tires", parent: "automotive" },
  { id: 189, name: "Car Tools", slug: "car-tools", parent: "automotive" },
  { id: 190, name: "Car Cleaning", slug: "car-cleaning", parent: "automotive" },
  { id: 191, name: "Car Lights", slug: "car-lights", parent: "automotive" },
  { id: 192, name: "Car Audio", slug: "car-audio", parent: "automotive" },
  { id: 193, name: "Car GPS", slug: "car-gps", parent: "automotive" },
  { id: 194, name: "Car Covers", slug: "car-covers", parent: "automotive" },
  { id: 195, name: "Car Seats", slug: "car-seats", parent: "automotive" },
  { id: 196, name: "Motorcycle Parts", slug: "motorcycle-parts", parent: "automotive" },
  { id: 197, name: "Motorcycle Gear", slug: "motorcycle-gear", parent: "automotive" },
  { id: 198, name: "Engine Parts", slug: "engine-parts", parent: "automotive" },
  { id: 199, name: "Brake Systems", slug: "brake-systems", parent: "automotive" },
  { id: 200, name: "Car Batteries", slug: "car-batteries", parent: "automotive" },
  { id: 201, name: "Car Repair Tools", slug: "car-repair-tools", parent: "automotive" },
  { id: 202, name: "Wheels", slug: "wheels", parent: "automotive" },
  { id: 203, name: "Air Fresheners", slug: "air-fresheners", parent: "automotive" },
  { id: 204, name: "Dash Cameras", slug: "dash-cameras", parent: "automotive" },
  { id: 205, name: "Parking Sensors", slug: "parking-sensors", parent: "automotive" },
  { id: 206, name: "Car Electronics Kits", slug: "car-electronics-kits", parent: "automotive" },
  { id: 207, name: "Suspension", slug: "suspension", parent: "automotive" },
  { id: 208, name: "Exhaust Systems", slug: "exhaust-systems", parent: "automotive" },
  { id: 209, name: "Filters", slug: "filters", parent: "automotive" },
  { id: 210, name: "Books", slug: "books", parent: null },
  { id: 211, name: "Novels", slug: "novels", parent: "books" },
  { id: 212, name: "School Books", slug: "school-books", parent: "books" },
  { id: 213, name: "Academic Books", slug: "academic-books", parent: "books" },
  { id: 214, name: "Business Books", slug: "business-books", parent: "books" },
  { id: 215, name: "Science Books", slug: "science-books", parent: "books" },
  { id: 216, name: "History Books", slug: "history-books", parent: "books" },
  { id: 217, name: "Religious Books", slug: "religious-books", parent: "books" },
  { id: 218, name: "Comics", slug: "comics", parent: "books" },
  { id: 219, name: "Children Books", slug: "children-books", parent: "books" },
  { id: 220, name: "Magazines", slug: "magazines", parent: "books" },
  { id: 221, name: "Programming Books", slug: "programming-books", parent: "books" },
  { id: 222, name: "Self Development", slug: "self-development", parent: "books" },
  { id: 223, name: "Language Books", slug: "language-books", parent: "books" },
  { id: 224, name: "Art Books", slug: "art-books", parent: "books" },
  { id: 225, name: "Cookbooks", slug: "cookbooks", parent: "books" },
  { id: 226, name: "Gaming", slug: "gaming", parent: null },
  { id: 227, name: "Video Games", slug: "video-games", parent: "gaming" },
  { id: 228, name: "PC Games", slug: "pc-games", parent: "gaming" },
  { id: 229, name: "Console Games", slug: "console-games", parent: "gaming" },
  { id: 230, name: "Gaming Accessories", slug: "gaming-accessories", parent: "gaming" },
  { id: 231, name: "Controllers", slug: "controllers", parent: "gaming" },
  { id: 232, name: "Gaming Chairs", slug: "gaming-chairs", parent: "gaming" },
  { id: 233, name: "Gaming Keyboards", slug: "gaming-keyboards", parent: "gaming" },
  { id: 234, name: "Gaming Mice", slug: "gaming-mice", parent: "gaming" },
  { id: 235, name: "VR Games", slug: "vr-games", parent: "gaming" },
  { id: 236, name: "Game Cards", slug: "game-cards", parent: "gaming" },
  { id: 237, name: "PlayStation Games", slug: "playstation-games", parent: "gaming" },
  { id: 238, name: "Xbox Games", slug: "xbox-games", parent: "gaming" },
  { id: 239, name: "Nintendo Games", slug: "nintendo-games", parent: "gaming" },
  { id: 240, name: "Gaming Headsets", slug: "gaming-headsets", parent: "gaming" },
  { id: 241, name: "Streaming Gear", slug: "streaming-gear", parent: "gaming" },
  { id: 242, name: "Gamepads", slug: "gamepads", parent: "gaming" },
  { id: 243, name: "Game Subscriptions", slug: "game-subscriptions", parent: "gaming" },
  { id: 244, name: "Gaming Software", slug: "gaming-software", parent: "gaming" },
  { id: 245, name: "Esports Gear", slug: "esports-gear", parent: "gaming" },
  { id: 246, name: "Gaming Tables", slug: "gaming-tables", parent: "gaming" },
  { id: 247, name: "Pet Supplies", slug: "pets", parent: null },
  { id: 248, name: "Dog Food", slug: "dog-food", parent: "pets" },
  { id: 249, name: "Cat Food", slug: "cat-food", parent: "pets" },
  { id: 250, name: "Pet Toys", slug: "pet-toys", parent: "pets" },
  { id: 251, name: "Pet Accessories", slug: "pet-accessories", parent: "pets" },
  { id: 252, name: "Pet Beds", slug: "pet-beds", parent: "pets" },
  { id: 253, name: "Pet Grooming", slug: "pet-grooming", parent: "pets" },
  { id: 254, name: "Bird Supplies", slug: "bird-supplies", parent: "pets" },
  { id: 255, name: "Fish Supplies", slug: "fish-supplies", parent: "pets" },
  { id: 256, name: "Aquarium", slug: "aquarium", parent: "pets" },
  { id: 257, name: "Pet Health", slug: "pet-health", parent: "pets" },
  { id: 258, name: "Pet Clothes", slug: "pet-clothes", parent: "pets" },
  { id: 259, name: "Training Tools", slug: "training-tools", parent: "pets" },
  { id: 260, name: "Leashes", slug: "leashes", parent: "pets" },
  { id: 261, name: "Collars", slug: "collars", parent: "pets" },
  { id: 262, name: "Pet Carriers", slug: "pet-carriers", parent: "pets" },
  { id: 263, name: "Food & Grocery", slug: "food", parent: null },
  { id: 264, name: "Beverages", slug: "beverages", parent: "food" },
  { id: 265, name: "Snacks", slug: "snacks", parent: "food" },
  { id: 266, name: "Organic Food", slug: "organic-food", parent: "food" },
  { id: 267, name: "Cooking Ingredients", slug: "cooking-ingredients", parent: "food" },
  { id: 268, name: "Rice", slug: "rice", parent: "food" },
  { id: 269, name: "Flour", slug: "flour", parent: "food" },
  { id: 270, name: "Sugar", slug: "sugar", parent: "food" },
  { id: 271, name: "Spices", slug: "spices", parent: "food" },
  { id: 272, name: "Meat", slug: "meat", parent: "food" },
  { id: 273, name: "Seafood", slug: "seafood", parent: "food" },
  { id: 274, name: "Frozen Food", slug: "frozen-food", parent: "food" },
  { id: 275, name: "Dairy", slug: "dairy", parent: "food" },
  { id: 276, name: "Bread", slug: "bread", parent: "food" },
  { id: 277, name: "Coffee", slug: "coffee", parent: "food" },
  { id: 278, name: "Tea", slug: "tea", parent: "food" },
  { id: 279, name: "Juices", slug: "juices", parent: "food" },
  { id: 280, name: "Soft Drinks", slug: "soft-drinks", parent: "food" },
  { id: 281, name: "Chocolates", slug: "chocolates", parent: "food" },
  { id: 282, name: "Canned Food", slug: "canned-food", parent: "food" },
  { id: 283, name: "Baby Food", slug: "baby-food", parent: "food" },
  { id: 284, name: "Office Supplies", slug: "office", parent: null },
  { id: 285, name: "Printers", slug: "printers", parent: "office" },
  { id: 286, name: "Paper", slug: "paper", parent: "office" },
  { id: 287, name: "Pens", slug: "pens", parent: "office" },
  { id: 288, name: "Notebooks", slug: "notebooks", parent: "office" },
  { id: 289, name: "Office Furniture", slug: "office-furniture", parent: "office" },
  { id: 290, name: "Staplers", slug: "staplers", parent: "office" },
  { id: 291, name: "Folders", slug: "folders", parent: "office" },
  { id: 292, name: "Markers", slug: "markers", parent: "office" },
  { id: 293, name: "Desks", slug: "desks", parent: "office" },
  { id: 294, name: "Chairs", slug: "chairs", parent: "office" },
  { id: 295, name: "Office Electronics", slug: "office-electronics", parent: "office" },
  { id: 296, name: "Files", slug: "files", parent: "office" },
  { id: 297, name: "Calculators", slug: "calculators", parent: "office" },
  { id: 298, name: "Whiteboards", slug: "whiteboards", parent: "office" },
  { id: 299, name: "Office Decor", slug: "office-decor", parent: "office" },
  { id: 300, name: "Binders", slug: "binders", parent: "office" },
  { id: 301, name: "Labels", slug: "labels", parent: "office" },
  { id: 302, name: "Ink", slug: "ink", parent: "office" },
  { id: 303, name: "Office Storage", slug: "office-storage", parent: "office" },
  { id: 304, name: "Desk Accessories", slug: "desk-accessories", parent: "office" },
  { id: 305, name: "Tools & Hardware", slug: "tools", parent: null },
  { id: 306, name: "Power Tools", slug: "power-tools", parent: "tools" },
  { id: 307, name: "Hand Tools", slug: "hand-tools", parent: "tools" },
  { id: 308, name: "Drills", slug: "drills", parent: "tools" },
  { id: 309, name: "Screwdrivers", slug: "screwdrivers", parent: "tools" },
  { id: 310, name: "Wrenches", slug: "wrenches", parent: "tools" },
  { id: 311, name: "Hammers", slug: "hammers", parent: "tools" },
  { id: 312, name: "Painting Tools", slug: "painting-tools", parent: "tools" },
  { id: 313, name: "Plumbing Tools", slug: "plumbing-tools", parent: "tools" },
  { id: 314, name: "Electrical Tools", slug: "electrical-tools", parent: "tools" },
  { id: 315, name: "Safety Tools", slug: "safety-tools", parent: "tools" },
  { id: 316, name: "Measuring Tools", slug: "measuring-tools", parent: "tools" },
  { id: 317, name: "Tool Kits", slug: "tool-kits", parent: "tools" },
  { id: 318, name: "Workshop Equipment", slug: "workshop-equipment", parent: "tools" },
  { id: 319, name: "Cutting Tools", slug: "cutting-tools", parent: "tools" },
  { id: 320, name: "Industrial Tools", slug: "industrial-tools", parent: "tools" },
  { id: 321, name: "Construction Tools", slug: "construction-tools", parent: "tools" },
  { id: 322, name: "Garden Tools", slug: "garden-tools", parent: "tools" },
  { id: 323, name: "Repair Kits", slug: "repair-kits", parent: "tools" },
  { id: 324, name: "Tool Storage", slug: "tool-storage", parent: "tools" },
  { id: 325, name: "Metal Tools", slug: "metal-tools", parent: "tools" },
  { id: 326, name: "Wood Tools", slug: "wood-tools", parent: "tools" },
  { id: 327, name: "Air Tools", slug: "air-tools", parent: "tools" },
  { id: 328, name: "Welding Tools", slug: "welding-tools", parent: "tools" },
  { id: 329, name: "Fasteners", slug: "fasteners", parent: "tools" },
  { id: 330, name: "Adhesives", slug: "adhesives", parent: "tools" },
  { id: 331, name: "Industrial", slug: "industrial", parent: null },
  { id: 332, name: "Manufacturing Tools", slug: "manufacturing-tools", parent: "industrial" },
  { id: 333, name: "Safety Equipment", slug: "safety-equipment", parent: "industrial" },
  { id: 334, name: "Packaging", slug: "packaging", parent: "industrial" },
  { id: 335, name: "Heavy Machinery", slug: "heavy-machinery", parent: "industrial" },
  { id: 336, name: "Warehouse Equipment", slug: "warehouse-equipment", parent: "industrial" },
  { id: 337, name: "Industrial Storage", slug: "industrial-storage", parent: "industrial" },
  { id: 338, name: "Factory Tools", slug: "factory-tools", parent: "industrial" },
  { id: 339, name: "Automation", slug: "automation", parent: "industrial" },
  { id: 340, name: "Industrial Electronics", slug: "industrial-electronics", parent: "industrial" },
  { id: 341, name: "Workwear", slug: "workwear", parent: "industrial" },
  { id: 342, name: "Protective Gear", slug: "protective-gear", parent: "industrial" },
  { id: 343, name: "Construction Gear", slug: "construction-gear", parent: "industrial" },
  { id: 344, name: "Measuring Devices", slug: "measuring-devices", parent: "industrial" },
  { id: 345, name: "Industrial Lighting", slug: "industrial-lighting", parent: "industrial" },
  { id: 346, name: "Logistics Tools", slug: "logistics-tools", parent: "industrial" },
  { id: 347, name: "Digital Products", slug: "digital", parent: null },
  { id: 348, name: "Software", slug: "software", parent: "digital" },
  { id: 349, name: "Subscriptions", slug: "subscriptions", parent: "digital" },
  { id: 350, name: "Gift Cards", slug: "gift-cards", parent: "digital" },
  { id: 351, name: "Online Courses", slug: "online-courses", parent: "digital" },
  { id: 352, name: "Web Hosting", slug: "web-hosting", parent: "digital" },
  { id: 353, name: "Domains", slug: "domains", parent: "digital" },
  { id: 354, name: "Cloud Services", slug: "cloud-services", parent: "digital" },
  { id: 355, name: "VPN", slug: "vpn", parent: "digital" },
  { id: 356, name: "Design Assets", slug: "design-assets", parent: "digital" },
  { id: 357, name: "Templates", slug: "templates", parent: "digital" },
  { id: 358, name: "Stock Photos", slug: "stock-photos", parent: "digital" },
  { id: 359, name: "E-books", slug: "e-books", parent: "digital" },
  { id: 360, name: "Music Licenses", slug: "music-licenses", parent: "digital" },
  { id: 361, name: "Plugins", slug: "plugins", parent: "digital" },
  { id: 362, name: "Apps", slug: "apps", parent: "digital" },
  { id: 363, name: "Miscellaneous", slug: "misc", parent: null },
  { id: 364, name: "Deals", slug: "deals", parent: "misc" },
  { id: 365, name: "Clearance", slug: "clearance", parent: "misc" },
  { id: 366, name: "Trending Products", slug: "trending-products", parent: "misc" },
  { id: 367, name: "Seasonal Items", slug: "seasonal-items", parent: "misc" },
  { id: 368, name: "Gift Ideas", slug: "gift-ideas", parent: "misc" },
  { id: 369, name: "New Arrivals", slug: "new-arrivals", parent: "misc" },
  { id: 370, name: "Limited Edition", slug: "limited-edition", parent: "misc" },
  { id: 371, name: "Flash Sale", slug: "flash-sale", parent: "misc" },
  { id: 372, name: "Bundles", slug: "bundles", parent: "misc" },
  { id: 373, name: "Refurbished", slug: "refurbished", parent: "misc" },
];

async function main() {
  const parents = categories.filter((c) => c.parent === null);
  const children = categories.filter((c) => c.parent !== null);

  console.log(`Creating ${parents.length} parent categories...`);
  for (const cat of parents) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });
  }

  console.log(`Creating ${children.length} child categories...`);
  for (const cat of children) {
    const parent = await prisma.category.findUnique({ where: { slug: cat.parent! } });
    if (!parent) {
      console.warn(`Parent not found for ${cat.name} (parent: ${cat.parent})`);
      continue;
    }
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, parentId: parent.id },
      create: { name: cat.name, slug: cat.slug, parentId: parent.id },
    });
  }

  console.log("Done!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
