import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categoryQueries: Record<string, string> = {
  electronics: "electronics,technology", smartphones: "smartphone,mobile",
  "android-phones": "android,phone", iphones: "iphone,apple",
  tablets: "tablet,ipad", laptops: "laptop,notebook",
  "gaming-laptops": "gaming,laptop", "desktop-pcs": "desktop,computer",
  monitors: "monitor,screen", "gaming-monitors": "gaming,monitor",
  cameras: "camera,photography", "dslr-cameras": "dslr,camera",
  "action-cameras": "action,camera,gopro", "security-cameras": "security,camera",
  "smart-watches": "smartwatch,watch", "fitness-bands": "fitness,band,fitbit",
  headphones: "headphones,audio", earbuds: "earbuds,wireless",
  speakers: "speaker,audio", "bluetooth-speakers": "bluetooth,speaker",
  "gaming-consoles": "gaming,console", playstation: "playstation,sony",
  xbox: "xbox,microsoft", nintendo: "nintendo,switch",
  "computer-accessories": "computer,accessories", "mobile-accessories": "mobile,accessories",
  chargers: "charger,cable", "power-banks": "powerbank,battery",
  cables: "cable,usb", routers: "router,wifi",
  "smart-home": "smart,home,iot", tvs: "television,tv",
  projectors: "projector,cinema", drones: "drone,quadcopter",
  printers: "printer,office", "vr-devices": "virtual,reality,headset",
  "graphic-cards": "graphics,card,gpu", processors: "processor,cpu,computer",
  "storage-devices": "storage,hard,drive,ssd", motherboards: "motherboard,computer",
  "cooling-fans": "cooling,fan,computer", "networking-devices": "networking,server",
  "car-electronics": "car,electronics,dashboard", "audio-systems": "audio,system,speaker",
  "smart-devices": "smart,device,tech",
  fashion: "fashion,clothing", "men-clothing": "men,fashion,clothing",
  "women-clothing": "women,fashion,dress", "kids-clothing": "kids,children,clothing",
  "t-shirts": "tshirt", shirts: "shirt,formal", jeans: "jeans,denim",
  jackets: "jacket,leather", coats: "coat,winter", shoes: "shoes,footwear",
  sneakers: "sneakers,shoes", "formal-shoes": "formal,shoes,leather",
  sandals: "sandals,summer", bags: "bag,fashion", handbags: "handbag,purse",
  backpacks: "backpack,school", watches: "watch,wristwatch", jewelry: "jewelry,gold",
  sunglasses: "sunglasses,eyewear", sportswear: "sportswear,activewear",
  underwear: "underwear,lingerie", hats: "hat", belts: "belt,leather",
  socks: "socks", "traditional-wear": "traditional,dress", "luxury-fashion": "luxury,fashion",
  swimwear: "swimwear,beach", dresses: "dress,fashion", skirts: "skirt,fashion",
  hoodies: "hoodie,sweatshirt", tracksuits: "tracksuit,sportswear",
  "sports-shoes": "sports,shoes", accessories: "fashion,accessories",
  wallets: "wallet,leather", "perfume-fashion": "perfume,fragrance",
  "home-kitchen": "home,kitchen,interior", furniture: "furniture,home",
  "bedroom-furniture": "bedroom,furniture", "living-room-furniture": "living,room,furniture",
  "kitchen-appliances": "kitchen,appliance", cookware: "cookware,cooking,pan",
  utensils: "kitchen,utensils", lighting: "lighting,lamp",
  "led-lights": "led,lights", curtains: "curtains,window",
  carpets: "carpet,rug", storage: "storage,organization",
  "cleaning-tools": "cleaning,supplies", "bathroom-items": "bathroom,accessories",
  mattresses: "mattress,bed", beds: "bed,furniture", tables: "table,furniture",
  chairs: "chair,furniture", "kitchen-storage": "kitchen,storage",
  "decor-items": "home,decor", "wall-art": "wall,art",
  clocks: "clock,wall", mirrors: "mirror,home",
  "gardening-tools": "gardening,tools", "outdoor-furniture": "outdoor,furniture",
  blenders: "blender,kitchen", "coffee-machines": "coffee,machine",
  "air-fryers": "air,fryer", "vacuum-cleaners": "vacuum,cleaner",
  "ironing-tools": "iron,clothes", "dish-racks": "dish,rack",
  "water-filters": "water,filter", fans: "fan,ceiling",
  heaters: "heater,warm", "kitchen-knives": "kitchen,knife",
  beauty: "beauty,cosmetics", skincare: "skincare,face", haircare: "hair,care",
  makeup: "makeup,cosmetics", perfumes: "perfume,fragrance",
  "body-care": "body,care,lotion", "beauty-devices": "beauty,device",
  "men-grooming": "men,grooming,beard", lipsticks: "lipstick,makeup",
  foundation: "foundation,makeup", shampoo: "shampoo,hair",
  conditioner: "conditioner,hair", "face-creams": "face,cream",
  serums: "serum,skincare", "eye-care": "eye,care", "nail-care": "nail,polish",
  "makeup-brushes": "makeup,brush", "hair-styling-tools": "hair,styling",
  "hair-oil": "hair,oil", "face-wash": "face,wash",
  deodorants: "deodorant,body",
  "baby-kids": "baby,kids", "baby-clothing": "baby,clothes,newborn",
  toys: "toys,kids", "baby-care": "baby,care", strollers: "stroller,baby",
  "feeding-items": "baby,feeding", diapers: "diaper,baby",
  "baby-beds": "baby,bed,crib", "kids-toys": "kids,toys",
  "educational-toys": "educational,toys", "baby-safety": "baby,safety",
  "baby-food": "baby,food", "kids-shoes": "kids,shoes",
  "baby-accessories": "baby,accessories", "baby-bath": "baby,bath",
  sports: "sports,fitness", "fitness-equipment": "fitness,equipment",
  "gym-accessories": "gym,accessories", dumbbells: "dumbbell,weight",
  "yoga-mats": "yoga,mat", camping: "camping,tent", cycling: "cycling,bike",
  football: "football,soccer", basketball: "basketball", swimming: "swimming,pool",
  tennis: "tennis,racket", "running-gear": "running,shoes",
  "outdoor-gear": "outdoor,gear", fishing: "fishing", hiking: "hiking,mountain",
  skating: "skating", climbing: "climbing,rock", "sports-wear": "sportswear",
  "training-equipment": "training,equipment", "protein-supplements": "protein,supplement",
  bikes: "bicycle,bike", "exercise-machines": "exercise,machine",
  treadmills: "treadmill", "home-gym": "home,gym", "boxing-gear": "boxing,gloves",
  "martial-arts": "martial,arts", "water-sports": "water,sports",
  "winter-sports": "winter,sports", "team-sports": "team,sports",
  "adventure-gear": "adventure,gear",
  automotive: "car,automotive", "car-accessories": "car,accessories",
  "oils-&-fluids": "motor,oil", tires: "car,tire",
  "car-tools": "car,tools", "car-cleaning": "car,wash",
  "car-lights": "car,headlight", "car-audio": "car,audio",
  "car-gps": "car,gps", "car-covers": "car,cover",
  "car-seats": "car,seat", "motorcycle-parts": "motorcycle,parts",
  "motorcycle-gear": "motorcycle,helmet", "engine-parts": "engine,parts",
  "brake-systems": "brake,system", "car-batteries": "car,battery",
  "car-repair-tools": "car,repair", wheels: "car,wheel",
  "air-fresheners": "car,freshener", "dash-cameras": "dash,camera",
  "parking-sensors": "parking,sensor", "car-electronics-kits": "car,electronics",
  suspension: "car,suspension", "exhaust-systems": "car,exhaust",
  filters: "car,filter",
  books: "books,library", novels: "novel,book", "school-books": "school,books",
  "academic-books": "academic,books", "business-books": "business,book",
  "science-books": "science,book", "history-books": "history,book",
  "religious-books": "religious,book", comics: "comic,book",
  "children-books": "children,book", magazines: "magazine",
  "programming-books": "programming,coding", "self-development": "self,development",
  "language-books": "language,learning", "art-books": "art,book",
  cookbooks: "cookbook,recipe",
  gaming: "gaming,setup", "video-games": "video,games", "pc-games": "pc,gaming",
  "console-games": "console,gaming", "gaming-accessories": "gaming,accessories",
  controllers: "game,controller", "gaming-chairs": "gaming,chair",
  "gaming-keyboards": "gaming,keyboard", "gaming-mice": "gaming,mouse",
  "vr-games": "virtual,reality", "game-cards": "gift,card",
  "playstation-games": "playstation,games", "xbox-games": "xbox,games",
  "nintendo-games": "nintendo,games", "gaming-headsets": "gaming,headset",
  "streaming-gear": "streaming,microphone", gamepads: "gamepad,controller",
  "game-subscriptions": "subscription,game", "gaming-software": "gaming,software",
  "esports-gear": "esports,gaming", "gaming-tables": "gaming,desk",
  pets: "pet,dog,cat", "dog-food": "dog,food", "cat-food": "cat,food",
  "pet-toys": "pet,toy", "pet-accessories": "pet,accessories",
  "pet-beds": "pet,bed", "pet-grooming": "pet,grooming",
  "bird-supplies": "bird,pet", "fish-supplies": "fish,aquarium",
  aquarium: "aquarium,fish", "pet-health": "pet,health",
  "pet-clothes": "pet,clothing", "training-tools": "pet,training",
  leashes: "dog,leash", collars: "dog,collar", "pet-carriers": "pet,carrier",
  food: "grocery,food", beverages: "beverages,drinks", snacks: "snacks",
  "organic-food": "organic,food", "cooking-ingredients": "cooking,ingredients",
  rice: "rice,grain", flour: "flour,baking", sugar: "sugar,food",
  spices: "spices,herbs", meat: "meat,fresh", seafood: "seafood,fish",
  "frozen-food": "frozen,food", dairy: "dairy,milk", bread: "bread,bakery",
  coffee: "coffee,beans", tea: "tea,leaves", juices: "juice,fruit",
  "soft-drinks": "soda,drinks", chocolates: "chocolate,candy",
  "canned-food": "canned,food",
  office: "office,stationery", paper: "paper,office", pens: "pen,writing",
  notebooks: "notebook,journal", "office-furniture": "office,furniture",
  staplers: "stapler,office", folders: "folder,file", markers: "marker",
  desks: "desk,office", "office-electronics": "office,electronics",
  files: "file,folder", calculators: "calculator", whiteboards: "whiteboard",
  "office-decor": "office,decor", binders: "binder", labels: "label",
  ink: "printer,ink", "office-storage": "office,storage",
  "desk-accessories": "desk,accessories",
  tools: "tools,hardware", "power-tools": "power,tools", "hand-tools": "hand,tools",
  drills: "drill", screwdrivers: "screwdriver", wrenches: "wrench",
  hammers: "hammer", "painting-tools": "painting,brush",
  "plumbing-tools": "plumbing,pipe", "electrical-tools": "electrical,tools",
  "safety-tools": "safety,helmet", "measuring-tools": "measuring,tool",
  "tool-kits": "tool,kit", "workshop-equipment": "workshop,workbench",
  "cutting-tools": "cutting,tool", "industrial-tools": "industrial,tools",
  "construction-tools": "construction,tools", "garden-tools": "garden,tools",
  "repair-kits": "repair,kit", "tool-storage": "tool,storage",
  "metal-tools": "metal,working", "wood-tools": "wood,working",
  "air-tools": "air,compressor", "welding-tools": "welding",
  fasteners: "fasteners", adhesives: "glue,adhesive",
  industrial: "industrial,warehouse", "manufacturing-tools": "manufacturing,tools",
  "safety-equipment": "safety,equipment", packaging: "packaging,box",
  "heavy-machinery": "heavy,machinery", "warehouse-equipment": "warehouse,forklift",
  "industrial-storage": "industrial,storage", "factory-tools": "factory,tools",
  automation: "automation,robot", "industrial-electronics": "industrial,electronics",
  workwear: "workwear,uniform", "protective-gear": "protective,gear",
  "construction-gear": "construction,worker", "measuring-devices": "measuring,device",
  "industrial-lighting": "industrial,lighting", "logistics-tools": "logistics,shipping",
  digital: "digital,technology", software: "software,programming",
  subscriptions: "subscription,service", "gift-cards": "gift,card",
  "online-courses": "online,learning", "web-hosting": "web,hosting",
  domains: "domain,internet", "cloud-services": "cloud,computing",
  vpn: "vpn,security", "design-assets": "design,graphic",
  templates: "template,website", "stock-photos": "photography,stock",
  "e-books": "ebook,book", "music-licenses": "music,audio",
  plugins: "plugin,software", apps: "mobile,apps",
  misc: "shopping,variety,gadgets", deals: "sale,discount",
  clearance: "clearance,sale", "trending-products": "trending,products",
  "seasonal-items": "seasonal,holiday", "gift-ideas": "gift,present",
  "new-arrivals": "new,arrivals", "limited-edition": "limited,edition",
  "flash-sale": "flash,sale", bundles: "bundle,pack",
  refurbished: "refurbished,electronics",
};

async function main() {
  const allCategories = await prisma.category.findMany();
  let updated = 0;

  for (const cat of allCategories) {
    const query = categoryQueries[cat.slug] || cat.slug.replace(/-/g, ",");
    const lock = cat.slug.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
    const image = `https://loremflickr.com/400/400/${query}?lock=${lock}`;
    await prisma.category.update({
      where: { id: cat.id },
      data: { image },
    });
    updated++;
    if (updated % 50 === 0) console.log(`${updated}/${allCategories.length}`);
  }

  console.log(`Done! ${updated} categories updated.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
